services:
  nginx:
    image: nginx
    container_name: nginx
    env_file:
      - .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
        - "${PORT}:${PORT}"
    restart: always
    volumes:
      - wordpress:/var/www/html
      - phpmyadmin:/var/www/phpmyadmin
    depends_on:
      wordpress:
        condition: service_healthy
      phpmyadmin:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f -H \"host:${DOMAIN_NAME}\" http://localhost/health || exit 1"]
      # test: ["CMD-SHELL", "curl -f -k https://localhost/health || exit 1"]
      # test: ["CMD-SHELL", "if [ \"${PORT}\" = \"443\" ]; then curl -f -k https://localhost/health || exit 1; else curl -f -H \"Host:${DOMAIN_NAME}\" http://localhost/health || exit 1; fi"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - cloud-1

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "--password=${MARIA_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - cloud-1

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - cloud-1
    
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    build:
      context: requirements/phpmyadmin
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
    - BLOWFISH_SECRET=${BLOWFISH_SECRET}
    restart: always
    volumes:
      - phpmyadmin:/var/www/phpmyadmin
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - cloud-1

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - cloud-1

networks:
  cloud-1:
    driver: bridge

volumes:
  wordpress:
  mariadb_data:
  phpmyadmin: