# This playbook removes the specified project folder on the target host group.
#
# USAGE:
# You must specify the target host group using the "target" variable.
# Examples:
#   ansible-playbook playbooks/remove_project_folder.yml -e "target=dev" --ask-become-pass
#   ansible-playbook playbooks/remove_project_folder.yml -e "target=prod"
#
# Note: dev required sudo password
# Note: The playbook checks if the project directory exists before attempting to remove it.
---
- name: Remove project folder
  hosts: "{{ target}}"
  become: yes
  tasks:
    # - name: print folder
    #   debug:
    #     msg: "app_dest_path: {{app_dest_path}}"
    
    - name: Check if project directory exists
      stat:
        path: "{{ app_dest_path}}"
      register: project_src_dir

    - name: Remove project folder (like executing rm -rf)
      ansible.builtin.file:
        path: "{{ app_dest_path }}"
        state: absent
      when: project_src_dir.stat.exists and project_src_dir.stat.isdir


# Recap -e extra vars:
# -e EXTRA_VARS, --extra-vars EXTRA_VARS
# set additional variables as key=value or YAML/JSON, if filename prepend with @. This argument may be specified multiple times.


# Recap state: absent
# If absent, directories will be recursively deleted, and files or symlinks will be unlinked. In the case of a directory, if diff is declared, you will see the files and folders deleted listed under path_contents. Note that absent will not cause ansible.builtin.file to fail if the path does not exist as the state did not change.