---
- name: Deploy .env file from template
  ansible.builtin.template:
    src: .env.j2 # il file .env.j2 si trova in app_config/templates/ e serve a generare dal vault il file .env
    dest: "{{ app_dest_path_compose }}/.env" # La destinazione finale del file .env
    owner: "{{ app_owner_user }}"
    group: "{{ app_owner_user }}"
    mode: '0600' # Permessi: solo il proprietario può leggere/scrivere (molto importante per i segreti!)
  #no_log: true # Impedisce che i contenuti sensibili del file appaiano nei log di Ansible
  become: yes
  become_user: "{{ app_owner_user }}"
  # notify: Restart Docker Compose Services 